Repository zer0-os/zNS-dapp, pull requests merged in 2021-08, with the labels that each got.

#116 Changed background to 4k image
  src/assets/background.jpg
Labels: enhancement

#117 Request cards show proper currency, rather than defaulting to WILD
  src/components/Tables/RequestTable/components/RequestActions.tsx
Labels: bug

#115 Add missing view/accept bid flow to owned domains table
  src/components/Tables/DomainTable/DomainTable.tsx
  src/components/Tables/DomainTable/components/ViewBids.tsx
Labels: bug

#122 NFT view galaxy background should fade
  src/components/Cards/PreviewCard/PreviewCard.module.css
  src/containers/NFTView/NFTView.module.css
  src/containers/NFTView/NFTView.tsx
  src/styles/main.css
Labels: enhancement

#121 Global search overflow issues
  src/components/NavBars/TitleBar/TitleBar.module.css
  src/components/NavBars/TitleBar/TitleBar.tsx
  src/pages/ZNS/ZNS.tsx
Labels: bug

#119 Bid Modal Tweaks
  src/containers/MakeABid/MakeABid.tsx
Labels: bug, enhancement

#131 Metamask connecting/reconnecting stuck forever fix
  src/components/ConnectToWallet/ConnectToWallet.tsx
  src/lib/hooks/provider-hooks.ts
Labels: bug

#132 If domain URL its invalid get user back to home after 2 seconds
  src/lib/hooks/useZnsDomain.tsx
Labels: bug

#134 Bid history should show your own bids
  src/components/Tables/DomainTable/DomainTable.tsx
  src/components/Tables/DomainTable/components/NumBids.tsx
  src/components/Tables/DomainTable/components/ViewBids.tsx
  src/containers/OwnedDomainsTable/OwnedDomainsTable.tsx
  src/lib/providers/BidProvider.tsx
Labels: bug

#143 my domains refresh list after accept bid
  src/containers/OwnedDomainsTable/OwnedDomainsTable.tsx
  src/lib/hooks/zNSDomainHooks.tsx
Labels: bug

#133 Coingecko should not render USD $WILD values if fails
  src/containers/BidList/BidList.tsx
  src/containers/MakeABid/MakeABid.tsx
  src/containers/NFTView/NFTView.tsx
  src/containers/Request/Request.tsx
  src/lib/providers/CurrencyProvider.tsx
  src/lib/tokenPrices.ts
Labels: bug
