Repository zer0-os/zNS-dapp, pull requests merged in 2021-09, with the labels that each got.

#123 Wrapping inactive zNA span in Mint Preview
  src/components/MintPreview/MintPreview.module.css
Labels: bug

#150 Added Fathom analytics link
  public/index.html
Labels: enhancement

#154 FIX Blank overlay if user press "make a bid" button disconnected
  src/containers/NFTView/NFTView.tsx
Labels: bug

#153 Switched to hi-res Wilder World logo
  src/components/NavBars/FilterBar/FilterBar.module.css
  src/components/NavBars/FilterBar/FilterBar.tsx
  src/components/NavBars/FilterBar/assets/WWLogo_SVG.svg
Labels: enhancement

#158 Fast-track Fathom analytics link to master
  public/index.html
Labels: enhancement

#157 Post-release mobile tweaks
  src/components/Buttons/IconButton/IconButton.tsx
  src/components/NavBars/TitleBar/TitleBar.module.css
  src/components/Overlay/Overlay.module.css
  src/components/Overlay/Overlay.tsx
  src/containers/NFTView/NFTView.module.css
  src/pages/ZNS/ZNS.tsx
  src/styles/main.css
Labels: enhancement, passed design review

#151 Updates to Image component to allow for video controls (including bugfixes for iOS)
  src/components/Artwork/Artwork.module.css
  src/components/Cards/PreviewCard/PreviewCard.tsx
  src/components/Image/Image.module.css
  src/components/Image/Image.tsx
  src/containers/MakeABid/MakeABid.tsx
  src/containers/NFTView/NFTView.tsx
  src/containers/Request/Request.tsx
  src/containers/TransferOwnership/TransferOwnership.tsx
Labels: bug, passed design review

#152 Back button should only navigate up the domain tree
  src/pages/ZNS/ZNS.tsx
Labels: bug, passed design review

#145 Changed my domains inactive buttons to display text instead
  src/components/Tables/DomainTable/components/ViewBids.tsx
Labels: enhancement

#130 Switch font to Inter
  public/index.html
  src/components/ArrowLink/ArrowLink.module.css
  src/components/Artwork/Artwork.module.css
  src/components/Artwork/Artwork.tsx
  src/components/Buttons/FilterButton/FilterButton.module.css
  src/components/Buttons/FutureButton/FutureButtonStyle.module.css
  src/components/Cards/NFTCard/NFTCard.module.css
  src/components/Cards/PreviewCard/PreviewCard.module.css
  src/components/Cards/PreviewCard/PreviewCard.tsx
  src/components/Confirmation/Confirmation.module.css
  src/components/ConnectToWallet/ConnectToWallet.tsx
  src/components/ConnectToWallet/Wallet.module.css
  src/components/CopyInput/CopyInput.js
  src/components/CopyInput/CopyInput.module.css
  src/components/HorizontalScroll/HorizontalScroll.module.css
  src/components/Image/Image.tsx
  src/components/Inputs/EtherInput/EtherInput.module.css
  src/components/Inputs/TextInput/TextInput.module.css
  src/components/Member/Member.module.css
  src/components/MintPreview/MintPreview.module.css
  src/components/NavBars/FilterBar/FilterBar.module.css
  src/components/NavBars/TabBar/TabBar.module.css
  src/components/NavBars/TitleBar/TitleBar.module.css
  src/components/NavBars/TitleBar/TitleBar.tsx
  src/components/Profile/Profile.module.css
  src/components/ProgressIndicators/StepBar/StepBar.module.css
  src/components/SearchBar/SearchBar.module.css
  src/components/Tables/BidTable/BidTable.module.css
  src/components/Tables/DomainTable/DomainTable.module.css
  src/components/Tables/DomainTable/DomainTable.tsx
  src/components/Tables/DomainTable/components/NFTCardActions.module.css
  src/components/Tables/RequestTable/RequestTable.module.css
  src/components/Tables/RequestTable/RequestTable.tsx
  src/components/ZNALink/ZNALink.module.css
  src/containers/BidList/BidList.module.css
  src/containers/MakeABid/MakeABid.module.css
  src/containers/MakeABid/MakeABid.tsx
  src/containers/MintNewNFT/MintNewNFT.module.css
  src/containers/MintNewNFT/sections/Staking.tsx
  src/containers/MintNewNFT/sections/Summary.tsx
  src/containers/NFTView/NFTView.module.css
  src/containers/NFTView/NFTView.tsx
  src/containers/OwnedDomainsTable/OwnedDomainsTable.tsx
  src/containers/Request/Request.module.css
  src/containers/Request/Request.tsx
  src/containers/TransferOwnership/TransferOwnership.module.css
  src/pages/ZNS/ZNS.tsx
  src/styles/Button.module.css
  src/styles/main.css
  src/styles/reset.css
Labels: enhancement, passed design review

#155 Promote develop to master
  public/index.html
  src/components/ArrowLink/ArrowLink.module.css
  src/components/Artwork/Artwork.module.css
  src/components/Artwork/Artwork.tsx
  src/components/Buttons/FilterButton/FilterButton.module.css
  src/components/Buttons/FutureButton/FutureButtonStyle.module.css
  src/components/Buttons/IconButton/IconButton.tsx
  src/components/Buttons/NumberButton/NumberButton.module.css
  src/components/Cards/NFTCard/NFTCard.module.css
  src/components/Cards/PreviewCard/PreviewCard.module.css
  src/components/Cards/PreviewCard/PreviewCard.tsx
  src/components/Confirmation/Confirmation.module.css
  src/components/ConnectToWallet/ConnectToWallet.tsx
  src/components/ConnectToWallet/Wallet.module.css
  src/components/CopyInput/CopyInput.js
  src/components/CopyInput/CopyInput.module.css
  src/components/HorizontalScroll/HorizontalScroll.module.css
  src/components/Image/Image.module.css
  src/components/Image/Image.tsx
  src/components/Inputs/EtherInput/EtherInput.module.css
  src/components/Inputs/TextInput/TextInput.module.css
  src/components/Member/Member.module.css
  src/components/MintPreview/MintPreview.module.css
  src/components/NavBars/FilterBar/FilterBar.module.css
  src/components/NavBars/FilterBar/FilterBar.tsx
  src/components/NavBars/FilterBar/assets/WWLogo_SVG.svg
  src/components/NavBars/TabBar/TabBar.module.css
  src/components/NavBars/TitleBar/TitleBar.module.css
  src/components/NavBars/TitleBar/TitleBar.tsx
  src/components/Overlay/Overlay.module.css
  src/components/Overlay/Overlay.tsx
  src/components/Profile/Profile.module.css
  src/components/ProgressIndicators/StepBar/StepBar.module.css
  src/components/SearchBar/SearchBar.module.css
  src/components/Tables/BidTable/BidTable.module.css
  src/components/Tables/DomainTable/DomainTable.module.css
  src/components/Tables/DomainTable/DomainTable.tsx
  src/components/Tables/DomainTable/components/NFTCardActions.module.css
  src/components/Tables/DomainTable/components/ViewBids.tsx
  src/components/Tables/RequestTable/RequestTable.module.css
  src/components/Tables/RequestTable/RequestTable.tsx
  src/components/ZNALink/ZNALink.module.css
  src/containers/BidList/BidList.module.css
  src/containers/MakeABid/MakeABid.module.css
  src/containers/MakeABid/MakeABid.tsx
  src/containers/MintNewNFT/MintNewNFT.module.css
  src/containers/MintNewNFT/sections/Staking.tsx
  src/containers/MintNewNFT/sections/Summary.tsx
  src/containers/NFTView/NFTView.module.css
  src/containers/NFTView/NFTView.tsx
  src/containers/OwnedDomainsTable/OwnedDomainsTable.tsx
  src/containers/Request/Request.module.css
  src/containers/Request/Request.tsx
  src/containers/TransferOwnership/TransferOwnership.module.css
  src/containers/TransferOwnership/TransferOwnership.tsx
  src/pages/ZNS/ZNS.tsx
  src/styles/Button.module.css
  src/styles/main.css
  src/styles/reset.css
Labels: release, passed design review

#161 Release 0.8.2
  public/index.html
  src/components/ArrowLink/ArrowLink.module.css
  src/components/Artwork/Artwork.module.css
  src/components/Artwork/Artwork.tsx
  src/components/Buttons/FilterButton/FilterButton.module.css
  src/components/Buttons/FutureButton/FutureButtonStyle.module.css
  src/components/Buttons/IconButton/IconButton.tsx
  src/components/Buttons/NumberButton/NumberButton.module.css
  src/components/Cards/NFTCard/NFTCard.module.css
  src/components/Cards/PreviewCard/PreviewCard.module.css
  src/components/Cards/PreviewCard/PreviewCard.tsx
  src/components/Confirmation/Confirmation.module.css
  src/components/ConnectToWallet/ConnectToWallet.tsx
  src/components/ConnectToWallet/Wallet.module.css
  src/components/CopyInput/CopyInput.js
  src/components/CopyInput/CopyInput.module.css
  src/components/HorizontalScroll/HorizontalScroll.module.css
  src/components/Image/Image.module.css
  src/components/Image/Image.tsx
  src/components/Inputs/EtherInput/EtherInput.module.css
  src/components/Inputs/TextInput/TextInput.module.css
  src/components/Member/Member.module.css
  src/components/MintPreview/MintPreview.module.css
  src/components/NavBars/FilterBar/FilterBar.module.css
  src/components/NavBars/FilterBar/FilterBar.tsx
  src/components/NavBars/FilterBar/assets/WWLogo_SVG.svg
  src/components/NavBars/TabBar/TabBar.module.css
  src/components/NavBars/TitleBar/TitleBar.module.css
  src/components/NavBars/TitleBar/TitleBar.tsx
  src/components/Overlay/Overlay.module.css
  src/components/Overlay/Overlay.tsx
  src/components/Profile/Profile.module.css
  src/components/ProgressIndicators/StepBar/StepBar.module.css
  src/components/SearchBar/SearchBar.module.css
  src/components/Tables/BidTable/BidTable.module.css
  src/components/Tables/DomainTable/DomainTable.module.css
  src/components/Tables/DomainTable/DomainTable.tsx
  src/components/Tables/DomainTable/components/NFTCardActions.module.css
  src/components/Tables/DomainTable/components/ViewBids.tsx
  src/components/Tables/RequestTable/RequestTable.module.css
  src/components/Tables/RequestTable/RequestTable.tsx
  src/components/ZNALink/ZNALink.module.css
  src/containers/BidList/BidList.module.css
  src/containers/MakeABid/MakeABid.module.css
  src/containers/MakeABid/MakeABid.tsx
  src/containers/MintNewNFT/MintNewNFT.module.css
  src/containers/MintNewNFT/sections/Staking.tsx
  src/containers/MintNewNFT/sections/Summary.tsx
  src/containers/NFTView/NFTView.module.css
  src/containers/NFTView/NFTView.tsx
  src/containers/OwnedDomainsTable/OwnedDomainsTable.tsx
  src/containers/Request/Request.module.css
  src/containers/Request/Request.tsx
  src/containers/TransferOwnership/TransferOwnership.module.css
  src/containers/TransferOwnership/TransferOwnership.tsx
  src/pages/ZNS/ZNS.tsx
  src/styles/Button.module.css
  src/styles/main.css
  src/styles/reset.css
Labels: release

#164 Cloudinary integration
  package-lock.json
  package.json
  src/cloudinary-react/index.d.ts
  src/components/Artwork/Artwork.module.css
  src/components/Artwork/Artwork.tsx
  src/components/Cards/NFTCard/NFTCard.tsx
  src/components/Cards/PreviewCard/PreviewCard.module.css
  src/components/Cards/PreviewCard/PreviewCard.tsx
  src/components/Cards/PreviewCard/index.tsx
  src/components/IPFSMedia/IPFSMedia.module.css
  src/components/IPFSMedia/IPFSMedia.tsx
  src/components/IPFSMedia/index.tsx
  src/components/IPFSMedia/types.ts
  src/components/NFTMedia/CloudinaryMedia.tsx
  src/components/NFTMedia/IPFSMedia.tsx
  src/components/NFTMedia/NFTMedia.module.css
  src/components/NFTMedia/config.ts
  src/components/NFTMedia/index.tsx
  src/components/NFTMedia/types.ts
  src/components/Overlay/Overlay.module.css
  src/components/index.js
  src/containers/MakeABid/MakeABid.tsx
  src/containers/MintNewNFT/MintNewNFT.module.css
  src/containers/NFTView/NFTView.tsx
  src/containers/Request/Request.tsx
  src/containers/TransferOwnership/TransferOwnership.tsx
  src/lib/utils/index.ts
Labels: enhancement

#166 Post Cloudinary bugfixes
  src/components/Overlay/Overlay.tsx
  src/components/Profile/Profile.tsx
  src/components/Tables/BidTable/BidTable.tsx
  src/components/Tables/DomainTable/DomainTable.tsx
  src/containers/NFTView/NFTView.tsx
  src/pages/ZNS/ZNS.tsx
Labels: bug

#167 Release 0.8.3
  package-lock.json
  package.json
  src/cloudinary-react/index.d.ts
  src/components/Artwork/Artwork.module.css
  src/components/Artwork/Artwork.tsx
  src/components/Cards/NFTCard/NFTCard.tsx
  src/components/Cards/PreviewCard/PreviewCard.module.css
  src/components/Cards/PreviewCard/PreviewCard.tsx
  src/components/Cards/PreviewCard/index.tsx
  src/components/IPFSMedia/IPFSMedia.module.css
  src/components/IPFSMedia/IPFSMedia.tsx
  src/components/IPFSMedia/index.tsx
  src/components/IPFSMedia/types.ts
  src/components/Image/Image.tsx
  src/components/NFTMedia/CloudinaryMedia.tsx
  src/components/NFTMedia/IPFSMedia.tsx
  src/components/NFTMedia/NFTMedia.module.css
  src/components/NFTMedia/config.ts
  src/components/NFTMedia/index.tsx
  src/components/NFTMedia/types.ts
  src/components/Overlay/Overlay.module.css
  src/components/Overlay/Overlay.tsx
  src/components/Profile/Profile.module.css
  src/components/Profile/Profile.tsx
  src/components/Tables/BidTable/BidTable.tsx
  src/components/Tables/DomainTable/DomainTable.tsx
  src/components/index.js
  src/containers/MakeABid/MakeABid.tsx
  src/containers/MintNewNFT/MintNewNFT.module.css
  src/containers/NFTView/NFTView.module.css
  src/containers/NFTView/NFTView.tsx
  src/containers/Request/Request.tsx
  src/containers/TransferOwnership/TransferOwnership.tsx
  src/lib/utils/index.ts
  src/pages/ZNS/ZNS.tsx
Labels: release

#168 Fix for 404 bug when attempting to load Cloudinary links
  src/components/NFTMedia/index.tsx
Labels: bug

#169 Release 0.8.4 - Cloudinary hotfixes
  src/components/NFTMedia/CloudinaryMedia.tsx
  src/components/NFTMedia/config.ts
  src/components/NFTMedia/index.tsx
  src/components/NFTMedia/types.ts
  src/containers/MakeABid/MakeABid.module.css
  src/containers/MakeABid/MakeABid.tsx
Labels: bug

#171 Basic AIR WILD auction countdown
  src/components/Banners/CountdownBanner/CountdownBanner.module.css
  src/components/Banners/CountdownBanner/CountdownBanner.tsx
  src/components/Banners/CountdownBanner/assets/avatar.png
  src/components/Banners/CountdownBanner/assets/bidarrow.svg
  src/components/Banners/CountdownBanner/assets/wilder.jpg
  src/components/index.js
  src/containers/NFTView/NFTView.module.css
  src/pages/ZNS/ZNS.tsx
Labels: enhancement

#170 Work/leo/update history with transfers
  src/containers/NFTView/NFTView.tsx
  src/lib/hooks/zNSDomainHooks.tsx
  src/lib/providers/ZNSDomainProvider.tsx
  src/lib/types.ts
  src/lib/zns/queries.ts
Labels: enhancement, in progress

#181 Performance improvements & infinite scroll round 1
  package-lock.json
  package.json
  src/App.tsx
  src/components/Artwork/Artwork.tsx
  src/components/Banners/CountdownBanner/CountdownBanner.tsx
  src/components/Buttons/FutureButton/FutureButton.tsx
  src/components/Cards/NFTCard/NFTCard.module.css
  src/components/Cards/NFTCard/NFTCard.tsx
  src/components/Cards/NFTCard/index.tsx
  src/components/Cards/PreviewCard/PreviewCard.tsx
  src/components/Cards/PreviewCard/index.tsx
  src/components/Inputs/TextInput/TextInput.tsx
  src/components/Member/Member.tsx
  src/components/MintPreview/MintPreview.tsx
  src/components/NFTMedia/CloudinaryMedia.tsx
  src/components/NFTMedia/config.ts
  src/components/NFTMedia/index.tsx
  src/components/NavBars/TitleBar/TitleBar.tsx
  src/components/Profile/Profile.tsx
  src/components/Tables/BidTable/BidTable.tsx
  src/components/Tables/DomainTable/DomainTable.tsx
  src/components/Tables/DomainTable/components/HighestBid.tsx
  src/components/Tables/DomainTable/components/NFTCardActions.tsx
  src/components/Tables/DomainTable/components/NumBids.tsx
  src/components/Tables/DomainTable/components/ViewBids.tsx
  src/components/Tables/GenericTable/GenericTable.module.css
  src/components/Tables/GenericTable/GenericTable.tsx
  src/components/Tables/GenericTable/assets/grid.svg
  src/components/Tables/GenericTable/assets/list.svg
  src/components/Tables/RequestTable/RequestTable.tsx
  src/components/Tables/RequestTable/data.tsx
  src/components/index.js
  src/containers/MakeABid/MakeABid.tsx
  src/containers/MintNewNFT/sections/Staking.tsx
  src/containers/MintNewNFT/sections/TokenInformation.tsx
  src/containers/NFTView/NFTView.tsx
  src/containers/Request/Request.tsx
  src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.module.css
  src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.tsx
  src/containers/Tables/SubdomainTable/BidProvider.tsx
  src/containers/Tables/SubdomainTable/SubdomainTable.tsx
  src/containers/Tables/SubdomainTable/SubdomainTableCard.module.css
  src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx
  src/containers/Tables/SubdomainTable/SubdomainTableRow.module.css
  src/containers/Tables/SubdomainTable/SubdomainTableRow.tsx
  src/containers/TransferOwnership/TransferOwnership.tsx
  src/containers/cards/CurrentDomainPreview/CurrentDomainPreview.tsx
  src/containers/index.js
  src/lib/hooks/useBasicController.tsx
  src/lib/hooks/useStakingController.tsx
  src/lib/hooks/useZnsDomain.tsx
  src/lib/hooks/zNSDomainHooks.tsx
  src/lib/providers/BidProvider.tsx
  src/lib/providers/CurrencyProvider.tsx
  src/lib/providers/CurrentDomainProvider.tsx
  src/lib/providers/StakingRequestProvider.tsx
  src/pages/ZNS/ZNS.tsx
Labels: enhancement

#182 Release 0.8.6
  package-lock.json
  package.json
  src/App.tsx
  src/components/Artwork/Artwork.tsx
  src/components/Banners/CountdownBanner/CountdownBanner.tsx
  src/components/Buttons/FutureButton/FutureButton.tsx
  src/components/Cards/NFTCard/NFTCard.module.css
  src/components/Cards/NFTCard/NFTCard.tsx
  src/components/Cards/NFTCard/index.tsx
  src/components/Cards/PreviewCard/PreviewCard.tsx
  src/components/Cards/PreviewCard/index.tsx
  src/components/Inputs/TextInput/TextInput.tsx
  src/components/Member/Member.tsx
  src/components/MintPreview/MintPreview.tsx
  src/components/NFTMedia/CloudinaryMedia.tsx
  src/components/NFTMedia/config.ts
  src/components/NFTMedia/index.tsx
  src/components/NavBars/TitleBar/TitleBar.tsx
  src/components/Profile/Profile.tsx
  src/components/Tables/BidTable/BidTable.tsx
  src/components/Tables/DomainTable/DomainTable.tsx
  src/components/Tables/DomainTable/components/HighestBid.tsx
  src/components/Tables/DomainTable/components/NFTCardActions.tsx
  src/components/Tables/DomainTable/components/NumBids.tsx
  src/components/Tables/DomainTable/components/ViewBids.tsx
  src/components/Tables/GenericTable/GenericTable.module.css
  src/components/Tables/GenericTable/GenericTable.tsx
  src/components/Tables/GenericTable/assets/grid.svg
  src/components/Tables/GenericTable/assets/list.svg
  src/components/Tables/RequestTable/RequestTable.tsx
  src/components/Tables/RequestTable/data.tsx
  src/components/index.js
  src/containers/MakeABid/MakeABid.tsx
  src/containers/MintNewNFT/sections/Staking.tsx
  src/containers/MintNewNFT/sections/TokenInformation.tsx
  src/containers/NFTView/NFTView.tsx
  src/containers/Request/Request.tsx
  src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.module.css
  src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.tsx
  src/containers/Tables/SubdomainTable/BidProvider.tsx
  src/containers/Tables/SubdomainTable/SubdomainTable.tsx
  src/containers/Tables/SubdomainTable/SubdomainTableCard.module.css
  src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx
  src/containers/Tables/SubdomainTable/SubdomainTableRow.module.css
  src/containers/Tables/SubdomainTable/SubdomainTableRow.tsx
  src/containers/TransferOwnership/TransferOwnership.tsx
  src/containers/cards/CurrentDomainPreview/CurrentDomainPreview.tsx
  src/containers/index.js
  src/lib/hooks/useBasicController.tsx
  src/lib/hooks/useStakingController.tsx
  src/lib/hooks/useZnsDomain.tsx
  src/lib/hooks/zNSDomainHooks.tsx
  src/lib/providers/BidProvider.tsx
  src/lib/providers/CurrencyProvider.tsx
  src/lib/providers/CurrentDomainProvider.tsx
  src/lib/providers/StakingRequestProvider.tsx
  src/pages/ZNS/ZNS.tsx
Labels: release

#180 Switch Fathom from Auto to Hash
  public/index.html
Labels: enhancement

#183 Better auction countdown banner
  src/components/Banners/CountdownBanner/CountdownBanner.module.css
  src/components/Banners/CountdownBanner/CountdownBanner.tsx
  src/components/Banners/CountdownBanner/countdown.json
  src/containers/Tables/SubdomainTable/SubdomainTable.tsx
  src/pages/ZNS/ZNS.tsx
Labels: enhancement, needs design review

#186 Better mobile wrap
  src/components/Banners/CountdownBanner/CountdownBanner.tsx
Labels: enhancement

#189 Client-side enforcement of lowercase domain names in Mint flow
  src/components/Inputs/TextInput/TextInput.tsx
  src/containers/MintNewNFT/MintNewNFT.tsx
  src/containers/MintNewNFT/sections/TokenInformation.tsx
  src/lib/providers/MintProvider.tsx
  src/lib/providers/StakingRequestProvider.tsx
Labels: enhancement
