Repository zer0-os/zNS-dapp, pull requests merged in 2021-12, with the labels that each got.

#315 Whitelist sale countdown fix
  src/containers/flows/MintWheels/index.tsx
  src/containers/flows/MintWheels/labels.tsx
  src/pages/ZNS/ZNS.tsx
  src/store/index.ts
Labels: bug

#317 Wait for public sale to start before refetching
  package.json
  src/containers/flows/MintWheels/index.tsx
  src/containers/flows/MintWheels/labels.tsx
Labels: enhancement

#310 Update attribute's title to match Figma design
  src/containers/other/NFTView/NFTView.module.scss
Labels: enhancement

#336 Use default wallet connector
  package-lock.json
  package.json
  src/App.tsx
  src/components/ConnectToWallet/ConnectToWallet.tsx
  src/containers/buttons/ConnectWalletButton/ConnectWalletButton.tsx
  src/containers/navigation/Navigator/Navigator.tsx
  src/containers/staking/DepositTable/DepositTable.tsx
  src/containers/staking/Deposits/Deposits.tsx
  src/containers/staking/StakePoolTable/StakePoolTable.helpers.tsx
  src/containers/staking/StakePoolTable/StakePoolTable.tsx
  src/containers/staking/StakePoolTable/StakePoolTableRow.tsx
  src/containers/staking/StakingContainer/StakingContainer.tsx
  src/containers/staking/flows/StakeFlow/StakeFlow.tsx
  src/containers/staking/flows/StakeFlow/steps/Stake/Stake.module.scss
  src/containers/staking/flows/StakeFlow/steps/Stake/Stake.tsx
  src/containers/staking/flows/components/PoolData/PoolData.tsx
  src/lib/hooks/provider-hooks.ts
  src/lib/providers/staking/StakingUserDataProvider.tsx
Labels: staking

#328 Artwork unit test
  src/components/Artwork/Artwork.test.tsx
  src/components/Artwork/Artwork.tsx
Labels: enhancement
