Repository zer0-os/zNS-dapp, pull requests merged in 2021-11, with the labels that each got.

#287 Release 0.10.13 - Image optimisations
  package.json
  src/components/NFTMedia/CloudinaryMedia.tsx
  src/containers/flows/MintWheels/steps/Info/Info.tsx
  src/containers/flows/MintWheels/steps/Loading/Loading.tsx
  src/containers/other/NFTView/NFTView.tsx
  src/lib/providers/MintProvider.tsx
Labels: enhancement

#288 Release 0.10.12 - Banner changes, remove polling
  package.json
  src/containers/flows/MintWheels/index.tsx
Labels: enhancement

#146 Approving domain request loading indicator and error message
  src/components/Tables/RequestTable/RequestTable.tsx
  src/lib/utils/index.ts
Labels: enhancement

#289 Release 0.10.15 - Added sale countdown
  package.json
  src/containers/flows/MintWheels/index.tsx
  src/containers/flows/MintWheels/labels.tsx
Labels: enhancement

#291 Release 0.10.16 - Polling and price changes
  package.json
  src/containers/flows/MintWheels/helpers.ts
  src/containers/flows/MintWheels/index.tsx
Labels: release

#294 Release 0.10.17 - Banner delay
  package.json
  src/containers/flows/MintWheels/index.tsx
Labels: enhancement

#293 Disabled pinch zooming with two fingers.
  package-lock.json
  public/index.html
  src/styles/main.scss
Labels: enhancement, passed design review

#300 Release 0.11.0
  .env.sample
  .github/pull_request_template.md
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Cards/PreviewCard/PreviewCard.module.scss
  src/components/NavBars/FilterBar/FilterBar.module.scss
  src/components/NavBars/FilterBar/FilterBar.tsx
  src/components/Tables/DomainTable/DomainTable.module.scss
  src/components/Tables/GenericTable/GenericTable.module.scss
  src/components/Tables/RequestTable/RequestTable.module.scss
  src/components/Tables/RequestTable/RequestTable.tsx
  src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx
  src/containers/Tables/SubdomainTable/SubdomainTableRow.tsx
  src/containers/flows/MakeABid/MakeABid.tsx
  src/containers/other/NFTView/NFTView.module.scss
  src/containers/other/NFTView/NFTView.tsx
  src/containers/other/Request/Request.tsx
  src/lib/hooks/useCurrency.test.ts
  src/lib/hooks/useCurrency.ts
  src/lib/hooks/useDidMount.tsx
  src/lib/ipfs.ts
  src/lib/providers/CurrencyProvider.tsx
  src/lib/testUtils/renderWithRedux.tsx
  src/lib/utils/index.ts
  src/pages/ZNS/ZNS.tsx
  src/store/currency/actionTypes.ts
  src/store/currency/actions.test.ts
  src/store/currency/actions.ts
  src/store/currency/currency.mockData.ts
  src/store/currency/reducer.test.ts
  src/store/currency/reducer.ts
  src/store/currency/sagas.test.ts
  src/store/currency/sagas.ts
  src/store/currency/selectors.test.ts
  src/store/currency/selectors.ts
  src/store/currency/types.ts
  src/store/reducers.ts
  src/store/sagas.ts
  src/styles/main.scss
Labels: release

#304 Release 0.11.1
  package-lock.json
  src/lib/ipfs.ts
  src/pages/ZNS/ZNS.tsx
Labels: release
