Repository zer0-os/zNS-dapp, pull requests merged in 2021-10, with the labels that each got.

#198 Mint Wheels flow tweaks
  src/containers/flows/MintWheels/helpers.ts
  src/containers/flows/MintWheels/index.tsx
  src/containers/flows/MintWheels/labels.tsx
  src/containers/flows/MintWheels/steps/Info/Info.tsx
  src/containers/flows/MintWheels/steps/SelectAmount/SelectAmount.module.css
  src/containers/flows/MintWheels/steps/SelectAmount/SelectAmount.tsx
  src/containers/flows/MintWheels/steps/SelectAmount/assets/check.svg
  src/lib/contracts.ts
  src/lib/providers/MintProvider.tsx
  src/lib/wheelSale.ts
Labels: enhancement, in progress

#200 Mint Wheels tweaks
  src/components/Banners/MintWheelsBanner/MintWheelsBanner.module.css
  src/components/Banners/MintWheelsBanner/MintWheelsBanner.tsx
  src/components/Banners/MintWheelsBanner/assets/bidarrow.svg
  src/components/Countdown/Countdown.tsx
  src/components/index.js
  src/containers/flows/MintWheels/index.tsx
  src/containers/flows/MintWheels/labels.tsx
  src/lib/addresses.ts
Labels: enhancement

#205 Release 0.9.1
  src/containers/other/NFTView/NFTView.tsx
  src/lib/zns/queries.ts
Labels: bug

#165 Various small style tweaks
  package-lock.json
  src/assets/arrow-back.svg
  src/assets/arrow-forward.svg
  src/components/Dropdowns/OptionDropdown/OptionDropdown.module.css
  src/components/NavBars/TitleBar/TitleBar.tsx
  src/components/Profile/Profile.module.css
  src/components/Tables/RequestTable/RequestTable.tsx
  src/components/ZNALink/ZNALink.tsx
Labels: enhancement, passed design review

#208 Replaced countdown banner with Serenity banner
  src/components/Banners/CountdownBanner/CountdownBanner.module.css
  src/components/Banners/CountdownBanner/CountdownBanner.tsx
  src/components/Banners/CountdownBanner/countdown.json
  src/components/Banners/MintWheelsBanner/MintWheelsBanner.module.css
  src/pages/ZNS/ZNS.tsx
Labels: enhancement

#209 Banner change (Serenity)
  package-lock.json
  package.json
  src/components/Banners/CountdownBanner/CountdownBanner.module.css
  src/components/Banners/CountdownBanner/CountdownBanner.tsx
  src/components/Banners/CountdownBanner/countdown.json
  src/components/Banners/MintWheelsBanner/MintWheelsBanner.module.css
  src/components/Confirmation/Confirmation.tsx
  src/components/TransferPreview/TranferPreview.module.css
  src/components/TransferPreview/TransferPreview.tsx
  src/lib/providers/TransferProvider.tsx
  src/lib/utils/timeCache.ts
  src/pages/ZNS/ZNS.tsx
Labels: enhancement

#218 Handle new NFT image URLs
  src/components/NFTMedia/index.tsx
  src/lib/metadata.ts
Labels: bug

#219 Hotfix for image_full handling
  src/components/Artwork/Artwork.tsx
  src/components/Cards/NFTCard/index.tsx
  src/components/Cards/PreviewCard/index.tsx
  src/components/NFTMedia/types.ts
  src/containers/flows/MakeABid/MakeABid.tsx
  src/containers/other/NFTView/NFTView.tsx
  src/containers/other/Request/Request.tsx
  src/lib/metadata.ts
  src/lib/types.ts
Labels: bug

#178 Future Buttons Colours Updated
  package-lock.json
  package.json
  src/components/Buttons/FutureButton/FutureButton.tsx
  src/components/Buttons/FutureButton/FutureButtonStyle.module.css
  src/components/ConnectToWallet/ConnectToWallet.tsx
Labels: enhancement, passed design review

#179 Bids History padding and glow bleeding zNAlink
  src/components/ZNALink/ZNALink.module.css
  src/components/ZNALink/ZNALink.tsx
  src/containers/other/NFTView/NFTView.module.css
Labels: enhancement, needs design review

#215 Updated history transfers with "from" and "to"
  src/containers/other/NFTView/NFTView.tsx
  src/lib/types.ts
  src/lib/zns/queries.ts
Labels: enhancement

#230 Mobile breakpoint for mail-list sign-up
  src/containers/flows/WheelsWaitlist/WheelsWaitlist.module.css
  src/containers/flows/WheelsWaitlist/index.tsx
Labels: enhancement

#232 Raffle registration flow
  src/components/ConnectToWallet/ConnectToWallet.tsx
  src/components/Countdown/Countdown.tsx
  src/containers/flows/MintWheels/index.tsx
  src/containers/flows/WheelsRaffle/RaffleRegistration/RaffleRegistration.module.css
  src/containers/flows/WheelsRaffle/RaffleRegistration/RaffleRegistration.tsx
  src/containers/flows/WheelsRaffle/RaffleRegistration/index.tsx
  src/containers/flows/WheelsRaffle/WaitlistRegistration/WaitlistRegistration.module.css
  src/containers/flows/WheelsRaffle/WaitlistRegistration/WaitlistRegistration.tsx
  src/containers/flows/WheelsRaffle/WaitlistRegistration/index.tsx
  src/containers/flows/WheelsRaffle/WaitlistRegistration/validation.ts
  src/containers/flows/WheelsRaffle/assets/discord.png
  src/containers/flows/WheelsRaffle/assets/discord.svg
  src/containers/flows/WheelsRaffle/assets/twitter.png
  src/containers/flows/WheelsRaffle/assets/twitter.svg
  src/containers/flows/WheelsRaffle/index.tsx
  src/containers/flows/WheelsWaitlist/index.tsx
  src/containers/index.js
  src/pages/ZNS/ZNS.tsx
Labels: enhancement

#234 Raffle registration hotfixes
  src/containers/flows/WheelsRaffle/index.tsx
Labels: enhancement

#245 Download button on NFT View
  src/components/Tooltip/Tooltip.module.scss
  src/components/Tooltip/Tooltip.tsx
  src/containers/other/NFTView/NFTView.module.scss
  src/containers/other/NFTView/NFTView.tsx
  src/containers/other/NFTView/assets/download.svg
  src/containers/other/NFTView/assets/share.svg
Labels: enhancement

#247 Hardcode domain aspect ratios for consistent image display
  src/components/Cards/NFTCard/NFTCard.module.scss
  src/components/Cards/NFTCard/NFTCard.tsx
  src/components/NFTMedia/CloudinaryMedia.tsx
  src/components/NFTMedia/NFTMedia.module.scss
  src/components/NFTMedia/index.tsx
  src/components/NFTMedia/types.ts
  src/components/Tables/GenericTable/GenericTable.tsx
Labels: enhancement

#246 Fix for incorrect file on asset download
  src/containers/other/NFTView/NFTView.module.scss
  src/containers/other/NFTView/NFTView.tsx
Labels: bug

#252 Release 0.10.1
  src/containers/other/NFTView/NFTView.tsx
Labels: release

#282 Release 0.10.10 - Halt auction
  package.json
  src/components/Banners/MintWheelsBanner/MintWheelsBanner.tsx
  src/containers/flows/MintWheels/helpers.ts
  src/containers/flows/MintWheels/index.tsx
  src/containers/flows/MintWheels/labels.tsx
Labels: enhancement

#283 Fix navigation bug
  package.json
  src/containers/Tables/SubdomainTable/SubdomainTable.tsx
Labels: bug
