Repository zer0-os/zNS-dapp, pull requests merged in 2022-04, with the labels that each got.

#454 refactor: Use context API for SDK use
  src/App.tsx
  src/lib/hooks/sdk/useZnsSdk.tsx
  src/lib/providers/ZnsSdkProvider.tsx
Labels: enhancement

#413 fix: Stake Pool table improvements
  package-lock.json
  src/components/Inputs/TextInput/TextInputWithTopPlaceHolder.tsx
  src/components/Tables/GenericTable/GenericTable.tsx
  src/containers/Tables/SubdomainTable/SubdomainTable.tsx
  src/containers/staking/Deposits/Deposits.module.scss
  src/containers/staking/Deposits/Deposits.tsx
  src/containers/staking/StakePoolTable/StakePoolTable.constants.ts
  src/containers/staking/StakePoolTable/StakePoolTable.tsx
  src/containers/staking/StakePoolTable/StakePoolTableRow.test.tsx
  src/containers/staking/StakePoolTable/StakePoolTableRow.tsx
Labels: bug

#453 fix(buy-now): Use standardised getMetadata method
  src/containers/flows/BuyNow/index.tsx
  src/containers/flows/SetBuyNow/index.tsx
  src/lib/hooks/useMetadata.ts
Labels: enhancement

#429 feat: static "Create A DAO" flow
  src/components/Wizard/Presets/Buttons.tsx
  src/components/Wizard/Presets/Confirmation.tsx
  src/components/Wizard/Wizard.tsx
  src/containers/DAO/DAOContainer.tsx
  src/containers/DAO/pages/MintDAO/MintDAO.constants.ts
  src/containers/DAO/pages/MintDAO/MintDAO.helpers.tsx
  src/containers/DAO/pages/MintDAO/MintDAO.test.tsx
  src/containers/DAO/pages/MintDAO/MintDAO.tsx
  src/containers/DAO/pages/MintDAO/MintDAO.types.ts
  src/containers/DAO/pages/MintDAO/MintDAOButton.tsx
  src/containers/DAO/pages/MintDAO/elements/MintDAOForm/MintDAOForm.constants.ts
  src/containers/DAO/pages/MintDAO/elements/MintDAOForm/MintDAOForm.module.scss
  src/containers/DAO/pages/MintDAO/elements/MintDAOForm/MintDAOForm.tsx
  src/containers/DAO/pages/MintDAO/elements/index.ts
  src/containers/DAO/pages/MintDAO/index.ts
  src/lib/hooks/useManyClickHandlers.ts
Labels: enhancement

#470 feat: Handle NFT View actions
  src/assets/external-link.svg
  src/components/Buttons/TextButton/TextButton.module.scss
  src/components/Buttons/TextButton/TextButton.tsx
  src/components/Detail/Detail.tsx
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/SideBar.tsx
  src/containers/buttons/BidButton/BidButton.tsx
  src/containers/flows/BuyNow/BuyNowButton.tsx
  src/containers/flows/CancelBid/CancelBid.tsx
  src/containers/flows/SetBuyNow/index.tsx
  src/containers/other/NFTView/NFTView.helpers.ts
  src/containers/other/NFTView/NFTView.tsx
  src/containers/other/NFTView/elements/Actions/Actions.module.scss
  src/containers/other/NFTView/elements/Actions/Actions.test.tsx
  src/containers/other/NFTView/elements/Actions/Actions.tsx
  src/containers/other/NFTView/elements/History/elements/HistoryItem.tsx
  src/containers/other/NFTView/elements/NFT/NFT.module.scss
  src/containers/other/NFTView/elements/NFT/NFT.tsx
  src/containers/other/NFTView/elements/Stats/Stats.tsx
  src/containers/other/NFTView/elements/TokenHashBoxes/TokenHashBoxes.tsx
  src/containers/other/NFTView/elements/index.ts
  src/containers/other/NFTView/hooks/useNftData.ts
  src/pages/ZNS/ZNS.tsx
  src/styles/main.scss
Labels: enhancement, don't merge

#471 feat: Adjust Preview styles to match Figma
  src/components/ArrowLink/ArrowLink.test.tsx
  src/components/ArrowLink/ArrowLink.tsx
  src/components/Preview/Preview.module.scss
  src/components/Preview/Preview.tsx
  src/containers/cards/CurrentDomainPreview/CurrentDomainPreview.tsx
  src/pages/ZNS/ZNS.tsx
Labels: enhancement

#473 feat: New profile page
  package-lock.json
  package.json
  src/App.tsx
  src/assets/more-vertical.svg
  src/components/CopyInput/CopyInput.js
  src/components/Dropdowns/OptionDropdown/OptionDropdown.tsx
  src/components/Profile/Profile.constants.ts
  src/components/Profile/Profile.module.scss
  src/components/Profile/Profile.tsx
  src/components/Profile/assets/eth.svg
  src/components/Profile/assets/qr.png
  src/components/Profile/assets/wilder.jpg
  src/components/Profile/mock.json
  src/components/Tables/GenericTable/GenericTable.module.scss
  src/components/Tables/GenericTable/GenericTable.tsx
  src/components/index.js
  src/constants/routes.ts
  src/containers/PageContainer/elements/Header/hooks/useHeaderHandlers.ts
  src/containers/PageContainer/elements/Modals/Modals.tsx
  src/containers/PageContainer/index.tsx
  src/containers/Tables/BidTable/BidTable.module.scss
  src/containers/Tables/BidTable/BidTable.tsx
  src/containers/Tables/BidTable/BidTableRow.module.scss
  src/containers/Tables/BidTable/BidTableRow.tsx
  src/containers/Tables/BidTable/index.tsx
  src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.constants.ts
  src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.tsx
  src/containers/Tables/OwnedDomainsTable/OwnedDomainsTableRow.tsx
  src/containers/flows/MakeABid/MakeABid.tsx
  src/containers/index.js
  src/containers/modals/ProfileModal/ProfileModal.tsx
  src/pages/Profile/Profile.module.scss
  src/pages/Profile/Profile.tsx
  src/pages/index.ts
Labels: enhancement

#475 Release 0.13.2
  package-lock.json
  package.json
  src/containers/staking/DepositTable/DepositTable.helpers.ts
Labels: release

#476 Release 0.13.3
  package-lock.json
  package.json
  src/components/NFTMedia/index.tsx
  src/constants/ipfs.ts
  src/lib/hooks/useDomainMetadata.tsx
  src/lib/hooks/useZnsDomain.tsx
  src/lib/ipfs.ts
  src/lib/metadata.ts
Labels: bug

#494 Release 0.14.2
  package.json
  src/containers/other/NFTView/elements/NFT/NFT.module.scss
  src/lib/ipfs.ts
Labels: bug, release

#529 feat: Mobile flows
  src/components/Banners/MintDropNFTBanner/MintDropNFTBanner.tsx
  src/components/Cards/ImageCard/ImageCard.module.scss
  src/components/Confirmation/Confirmation.module.scss
  src/components/Confirmation/Confirmation.tsx
  src/components/ConnectToWallet/ConnectToWallet.tsx
  src/components/ConnectToWallet/Wallet.module.scss
  src/components/SideBar/SideBar.module.scss
  src/components/Tables/GenericTable/GenericTable.module.scss
  src/components/Tables/GenericTable/GenericTable.tsx
  src/components/Wizard/Presets/Buttons.module.scss
  src/components/Wizard/Presets/NFTDetails.module.scss
  src/components/Wizard/Wizard.module.scss
  src/components/Wizard/Wizard.tsx
  src/constants/nav.ts
  src/containers/PageContainer/PageContainer.constants.ts
  src/containers/PageContainer/PageContainer.module.scss
  src/containers/PageContainer/elements/Header/Header.tsx
  src/containers/PageContainer/elements/Header/_header.scss
  src/containers/PageContainer/elements/Header/elements/ConnectWalletButton/ConnectWalletButton.tsx
  src/containers/PageContainer/elements/Header/elements/ConnectWalletButton/hooks/useConnectWalletButtonData.ts
  src/containers/PageContainer/elements/Touchbar/Touchbar.module.scss
  src/containers/PageContainer/elements/Touchbar/Touchbar.tsx
  src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.tsx
  src/containers/Tables/OwnedDomainsTable/OwnedDomainsTableCard.module.scss
  src/containers/Tables/OwnedDomainsTable/OwnedDomainsTableCard.tsx
  src/containers/Tables/SubdomainTable/SubdomainTableCard.module.scss
  src/containers/flows/MakeABid/MakeABid.module.scss
  src/containers/flows/MintDropNFT/MintDropNFTWizard.module.scss
  src/containers/flows/MintDropNFT/MintDropNFTWizard.tsx
  src/containers/flows/MintDropNFT/index.tsx
  src/containers/flows/MintDropNFT/steps/SelectAmount/SelectAmount.tsx
  src/containers/flows/MintNewNFT/MintNewNFT.module.scss
  src/containers/flows/MintNewNFT/MintNewNFT.tsx
  src/containers/flows/MintNewNFT/sections/Summary.tsx
  src/containers/flows/MintNewNFT/sections/TokenInformation.tsx
  src/containers/lists/BidList/BidList.module.scss
  src/containers/prompts/ConnectWalletPrompt/ConnectWalletPrompt.tsx
  src/containers/staking/DepositTable/DepositTable.module.scss
  src/containers/staking/DepositTable/DepositTable.tsx
  src/containers/staking/DepositTable/DepositTableCard.module.scss
  src/containers/staking/DepositTable/DepositTableCard.tsx
  src/containers/staking/Deposits/Deposits.module.scss
  src/containers/staking/Deposits/Deposits.tsx
  src/containers/staking/StakeModule/StakeModule.module.scss
  src/containers/staking/StakeModule/StakeModule.tsx
  src/containers/staking/StakePoolTable/StakePoolTable.tsx
  src/containers/staking/StakePoolTable/StakePoolTableCard.module.scss
  src/containers/staking/StakePoolTable/StakePoolTableCard.tsx
  src/containers/staking/StakePoolTable/StakePoolTableRow.tsx
  src/containers/staking/StakingContainer/StakingContainer.tsx
  src/containers/staking/flows/ClaimFlow/ClaimFlow.module.scss
  src/containers/staking/flows/ClaimFlow/ClaimFlow.tsx
  src/containers/staking/flows/StakeFlow/StakeFlow.module.scss
  src/containers/staking/flows/StakeFlow/StakeFlow.tsx
  src/containers/staking/flows/StakeFlow/steps/Stake/Stake.tsx
  src/containers/staking/flows/components/PoolData/PoolData.module.scss
  src/containers/staking/flows/components/PoolData/PoolData.tsx
  src/pages/Profile/Profile.module.scss
  src/styles/main.scss
  src/styles/variables/_dimensions.scss
Labels: enhancement

#514 feat: Add Wilder Beasts DAO
  package-lock.json
  package.json
  src/constants/daos.ts
Labels: enhancement
