Repository zer0-os/zNS-dapp, pull requests merged in 2022-01, with the labels that each got.

#348 Release 0.10.30 - Hide raffle banner
  package.json
  src/pages/ZNS/ZNS.tsx
Labels: release

#351 Release 0.2.0
  package-lock.json
  package.json
  src/containers/staking/Deposits/Deposits.tsx
  src/lib/currency.ts
Labels: enhancement

#361 feat(domain-history): fix invalid urls for address in list
  src/containers/other/NFTView/NFTView.tsx
Labels: ready for merge
